dist: bionic
language: rust
rust:
  - stable
  - beta
  - nightly

# matrix:
#   allow_failures:
#     - rust: stable
#     - rust: beta

cache: cargo

script:
  - cargo build
  - cargo clean
  - cargo test

addons:
  apt:
    packages:
      - cmake
      - gfortran
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libiberty-dev
      - liblapacke-dev
      - libopenblas-dev
      - gcc
